const BACK_ACTION = 'BACK_ACTION';
const BACK_TO_SETTINGS_ACTION = 'BACK_TO_SETTINGS_ACTION';
const WEATHER_MENU_ACTION = 'WEATHER_MENU_ACTION';
const SETTINGS_MENU_ACTION = 'SETTINGS_MENU_ACTION';
const SETTINGS_NOTIFICATION_MENU_ACTION = 'SETTINGS_NOTIFICATION_MENU_ACTION';

module.exports = {
  BACK_ACTION,
  BACK_TO_SETTINGS_ACTION,
  WEATHER_MENU_ACTION,
  SETTINGS_MENU_ACTION,
  SETTINGS_NOTIFICATION_MENU_ACTION,
};
