const INPUT_STATE_CITY_NAME = 'INPUT_STATE_CITY_NAME';
const INPUT_STATE_NOTIFICATIONS_TIME = 'INPUT_STATE_NOTIFICATIONS_TIME';
const INPUT_STATE_NOTIFICATIONS_CITY = 'INPUT_STATE_NOTIFICATIONS_CITY';

module.exports = {
  INPUT_STATE_CITY_NAME,
  INPUT_STATE_NOTIFICATIONS_TIME,
  INPUT_STATE_NOTIFICATIONS_CITY,
};
